### ISSUE TITLE
so menuhax and browserhax doest work on 10.6

### ISSUE THREAD

**Issue by ashhax14** [yellows8/3ds_browserhax_common#23]
Is there any chance it will be on 10.6? Because the new Downgrade software is very tempting.Good luck :).

**Comment by yellows8** [comment]
It will be a while before I _really_ start _working_ on more freehax(but I don't really support downgrading either).

**Comment by warchicken** [comment]
I'm hoping it will freehax its my only option for home brew can't afford other options, browserhax is the only alternative for those of us that updated without wanting to or by accidents out of our control(my kid updated  without knowing what he was doing) please. Help us I only enjoy home brew for 3 days

**Comment by yellows8** [comment]
"can't afford" Even with Nintendo Selects .....

**Comment by warchicken** [comment]
I have smashbros (physical cartridge) it was my first 3ds game and I have tried my frien numerous times the smashhax and looks like I can't, packets stuck at 73, I know its complicated but I've been giving a shot tirelessly, its my only option since browserhax got block, my version is 1.1.5 since I bought cloud and corrin( I wanted all characters) but I didn't mind loosing them so I erased updates and got v1.0.1. I even found a pcap for that version and tried the had.. No luck ... And then I remember how easy it was with browserhax and it gets me sad... And brother no I can afford Nintendo selects my economic situation is hard ( im only income for family of four)I got my 3dsxl and first game( I only have two) with a lot of sacrifice after working a lot I tought I deserved it so I finally got one!! So you see browserhax was very important for us who can't afford any games, and I thank you for your time knowing that also you have your own life and problems and even so you take out of your time to develop those marvelous programs for us unknow people, I thank you for those 3 days I really got to enjoy my n3ds, thank you for browserhax you really gave us an option,

**Comment by warchicken** [comment]
If only there's could be a way to stop sysnand from asking for updates that way my situation will never happen to anyone else, thanks brother, I'm right now in v10.7 ( was in 10.5 went to 9.2 for 3 days after months of waiting and again to 10.7 thanks to my kids curiosity)

**Comment by warchicken** [comment]
Oh and when it happened I had wifi disabled, looks like at some time it downloaded the update and was just waiting for confirmation to install it, wich my kid did in the 3 seconds I look at another direction to pay attention to something my little daughter was saying
