### ISSUE TITLE
3ds_arm11code.s:1908: Error: branch out of range

### ISSUE THREAD

**Issue by Crystallinqq** [yellows8/3ds_browserhax_common#50]
Got this error while trying to compile 3ds_arm11code.s!

**Comment by yellows8** [comment]
That could only happen if you modified the .s enough....

**Comment by Crystallinqq** [comment]
I got it working btw i used the assembly file straight from the source!

**Comment by shinji257** [comment]
I came across this issue just recently.  Seems that the distro provided arm cross compiler (at least on Ubuntu) can trigger this for whatever reason.  If anyone comes across this then try using the one in devkitARM instead.  That one worked fine.

Just wanted to note it here rather than make a new ticket.
